### ISSUE TITLE
"Cancel" is unexpected when confirming closing

### ISSUE THREAD

**Issue by nyurik** [cujojs/meld#30]
After merging GIT conflict, 1) it was a bit hard to figure out how to get back to the file list, and 2) when switching to file list Meld asked me if I wanted to "mark file as resolved". I realized that I wasn't done, so I hit "escape" ("cancel" button), and instead of being taken back to the comparison, I was taken to the file list. A better behavior would be "cancel" = return to editing, "resolve", "don't resolve" (might need better naming).  Thanks!

**Comment by briancavalier** [comment]
This repository is for the JavaScript AOP library, meld.js.  It sounds like you're looking for [this Meld](http://meldmerge.org) :smile:
