### ISSUE TITLE
Advices on Callbacks

### ISSUE THREAD

**Issue by johannes-z** [cujojs/meld#38]
Is there a way to use advices on callbacks? F.e. I have an object with a function that receives an anonymous function. I want to log this callback function (`fn` in the following code snippet). If I only trace `beforeEach` I get all the registered callback functions, but I can't (obviously) access it's receiving arguments.

```js
VueRouter.prototype.beforeEach = function beforeEach (fn) {
  this.beforeHooks.push(fn)
};
```

**Comment by unscriptable** [comment]
Hey @johannes-z.  This seems possible.  Here's my quick attempt at it (totally untested!):

```js
import { before, around } from 'meld'

// Returns a function that advises the last argument of each method that
// matches the `match` parameter.  The last argument must be callable
// (e.g. a function).
export const adviseLastArg
    = advisor => (object, match, cbAdvice) => {
        const advice
            = ({ args, proceedApply }) => {
              // Advise last argument:
              const callback = advisor(args[args.length - 1], cbAdvice)
              // Re-create and apply arguments:
              const newArgs = args.slice(args.length - 1).concat(callback)
              return proceedApply(newArgs)
            }
        return around(object, match, advice)
    }

// Create a before advisor for the last argument.
const beforeCallback = adviseLastArg(before)

// Our orignal method:
VueRouter.prototype.beforeEach
    = function (fn) {
        this.beforeHooks.push(fn)
    }

// Our advised method that logs arguments of the callback (last argument):
beforeCallback(
    VueRouter.prototype,
    'beforeEach',
    // This is your advice for the callback function:
    (...args) => console.log(...args)
)
```

Does this make sense?

I think almost entirely in ES6 these days, but if you need me to translate it back to ES5, I will. :)

**Comment by johannes-z** [comment]
Thanks @unscriptable. That's pretty cool, I probably wouldn't have come up with this myself. Unfortunately the `beforeCallback` advice is never called (I tried both the `VueRouter.prototype` and the instantiated object). 

edit: This is how I add callbacks to `beforeEach`:

```js
const router = new VueRouter({ options })
router.beforeEach((to, from, next) => {
  console.log('beforeEach called')
  next()
})
```

edit2: I created a [repository](https://github.com/johannes-z/meld-callbacks) with a simple project to make this easier to communicate. The project reflects my actual use case, and I get this output: 

```
constructor called ...
test called ...
cb called ...
```

**Comment by unscriptable** [comment]
Nice! Cloning your repo now.

**Comment by briancavalier** [comment]
I think I came up with something similar to @unscriptable, but figured I'd put it out here in case it helps:

```js
import { before, around } from 'meld'

const log = (...args) => console.log(..args)

// Assume the first arg is a callback function, advise it, and
// then proceed with the new first arg plus the rest of the original args
const logCallbackArgs = ({ args, proceed }) =>
  proceed(before(args[0], log), ...args.slice(1))

around(VueRouter.prototype, 'beforeEach', logCallbackArgs)
```

IOW, advise VueRouter.prototype.beforeEach such that it, in turn, advises all incoming callback functions.

One problem I can see with this approach is that the function that gets pushed into the `beforeHooks` array is a *different function* than the one that was passed to `beforeEach`.  If there is a corresponding "removeBeforeEach" or somesuch, that a caller can use to unregister a beforeHook, that won't work anymore.  I can think of several ways to solve that, but hopefully we don't have to cross that bridge :)

**Comment by unscriptable** [comment]
Nice one, @briancavalier.  It's definitely less code to advise the first argument in ES6. :)  I love how tiny your solution is.

@johannes-z: I found my dumb mistake and I'm pushing the code...

**Comment by unscriptable** [comment]
@johannes-z: https://github.com/johannes-z/meld-callbacks/pull/1

**Comment by johannes-z** [comment]
This is awesome. Thank's a lot guys!

**Comment by briancavalier** [comment]
Nice work, @unscriptable :+1:
