### ISSUE TITLE
Advice multiple objects

### ISSUE THREAD

**Issue by agomezcafeto** [cujojs/meld#39]
It is possible to advise multiple objects ? for example:

meld.after([objects], [methods], function () { ...

**Comment by briancavalier** [comment]
Hi @agomezcafeto.  There's no builtin API for that, but you do it easily by mapping an array of objects.

```js
const removers = arrayOfObjects.map(object =>
  meld.after(object, [methods], function () { ... }))
```

Hope that helps.  Cheers!

**Comment by agomezcafeto** [comment]
thanks, yes I did that
