### ISSUE TITLE
Promises are not working

### ISSUE THREAD

**Issue by vikram1992** [cujojs/meld#44]

**Comment by briancavalier** [comment]
Hi @vikram1992.  Could you please provide more information and a test case to show what you're trying to do?  Thanks!

**Comment by vikram1992** [comment]
Yeah basically m capturing sequelize errors n throwing custom developer messages. The thing is that the sequelize returns promise and my aop doesn't get triggered. Can you please help me

**Comment by vikram1992** [comment]
Hi, I have solve the issue with afterReturning handler.

**Comment by briancavalier** [comment]
@vikram1992 Thanks for more info, and I'm glad you figured it out 😄 Cheers!
